### ISSUE TITLE
[Suggestion] Add Milk Tag to DP Milk bottles

### ISSUE THREAD

**Issue by ffuentesm** [Tfarcenim/Daves-Potioneering#25]
could you add a #forge:milk tag to the milk bottles from this mod? 
That way it will be compatible with other mods, such as Farmer's Delight.

**Comment by Tfarcenim** [comment]
Not possible because milk in this mod is a potion derivative, not a distinct item.

**Comment by IdrisQe** [comment]
So, since this isn't possible, could we get a config option to disable Milk Bottles then, so they don't clash with Milk Bottles from other mods? I know we would lose out on unique features of these milk bottles like the Milk-in-potions, and Splash Bottles of Milk, but it would be a nice option to keep consistency.
